name: enhanced_drop_down
description: A completely customizable drop down widget that comes with a label built in. You can customize the label, the data, the default value and more.
version: 0.3.4+0
homepage: https://github.com/TomerPacific

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: "^3.19.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter: